replicaCount: 2
image:
  repository: <your-ecr-repo>
  tag: latest
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 80
env:
  JWT_SECRET: your_jwt_secret
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
