apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DB_HOST: <db-host>
  DB_USER: <db-user>
  DB_PASS: <db-pass>
  DB_NAME: urls
  JWT_SECRET: {{ .Values.env.JWT_SECRET }}
  API_USER: admin
  API_PASS: secret