apiVersion: v1
kind: Service
metadata:
  name: url-shortener
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: url-shortener
