name: CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push Docker Image
        run: |
          docker build -t $ECR_IMAGE .
          docker tag $ECR_IMAGE $ECR_URI
          docker push $ECR_URI
        env:
          ECR_IMAGE: url-shortener
          ECR_URI: ${{ secrets.ECR_URI }}
      - name: Deploy to EKS via Helm
        run: |
          helm upgrade --install url-shortener ./chart --set image.repository=$ECR_URI --namespace default
